POST http://localhost:5000/api/imgdemo/
Content-Type: application/json

{
    "name":"vinhlv@yopmail.com",
    "data":[
        {
            "src":"123",
            "name":"123"
        },
        {
            "src":"123",
            "name":"123"
        }
    ]
}