POST http://localhost:5000/api/imgview/update
Content-Type: application/json

{
    "name":"skill park 4",
    "data":[
        {
            "src":"1",
            "name":"hihi"
        },
        {
            "src":"hihi",
            "name":"hihi"
        }
    ]
}